const datosBancarios2 =  [
    {
        "AC_NO":  240806828,
        "TRN_REF_NO":  "240A061260990001",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "A13",
        "DRCR_IND":  "D",
        "TRN_DESC":  "IVA COBRADO",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  6650,
        "EXTERNAL_REF_NO":  "0991146018845290",
        "MODULE":  "RT",
        "TXN_TYPE":  "TC",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551475
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "240A0612609900RR",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "A13",
        "DRCR_IND":  "D",
        "TRN_DESC":  "IVA COBRADO",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  6650,
        "EXTERNAL_REF_NO":  "0991151039486392",
        "MODULE":  "RT",
        "TXN_TYPE":  "TC",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551511
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "240A0612609900DW",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "A13",
        "DRCR_IND":  "D",
        "TRN_DESC":  "IVA COBRADO",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  6650,
        "EXTERNAL_REF_NO":  "0991146470113142",
        "MODULE":  "RT",
        "TXN_TYPE":  "TC",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556449
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "240A0612609900DX",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "A13",
        "DRCR_IND":  "D",
        "TRN_DESC":  "IVA COBRADO",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  6650,
        "EXTERNAL_REF_NO":  "0991150250478024",
        "MODULE":  "RT",
        "TXN_TYPE":  "TC",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556487
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A0612609900DW",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "A13",
        "DRCR_IND":  "D",
        "TRN_DESC":  "IVA COBRADO",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  6650,
        "EXTERNAL_REF_NO":  "0991148133693168",
        "MODULE":  "RT",
        "TXN_TYPE":  "TC",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551487
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A0612609900DX",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "A13",
        "DRCR_IND":  "D",
        "TRN_DESC":  "IVA COBRADO",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  6650,
        "EXTERNAL_REF_NO":  "0991148509528098",
        "MODULE":  "RT",
        "TXN_TYPE":  "TC",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551499
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A0612609900DY",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "A13",
        "DRCR_IND":  "D",
        "TRN_DESC":  "IVA COBRADO",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  6650,
        "EXTERNAL_REF_NO":  "0991155098158948",
        "MODULE":  "RT",
        "TXN_TYPE":  "TC",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551549
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A061260990001",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "A13",
        "DRCR_IND":  "D",
        "TRN_DESC":  "IVA COBRADO",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  6650,
        "EXTERNAL_REF_NO":  "0991147311045561",
        "MODULE":  "RT",
        "TXN_TYPE":  "TC",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556461
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A061260990002",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "A13",
        "DRCR_IND":  "D",
        "TRN_DESC":  "IVA COBRADO",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  6650,
        "EXTERNAL_REF_NO":  "0991149292408029",
        "MODULE":  "RT",
        "TXN_TYPE":  "TC",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556475
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A061260990003",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "A13",
        "DRCR_IND":  "D",
        "TRN_DESC":  "IVA COBRADO",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  6650,
        "EXTERNAL_REF_NO":  "0991152360538751",
        "MODULE":  "RT",
        "TXN_TYPE":  "TC",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556499
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A061260990004",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "A13",
        "DRCR_IND":  "D",
        "TRN_DESC":  "IVA COBRADO",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  6650,
        "EXTERNAL_REF_NO":  "0991153511212474",
        "MODULE":  "RT",
        "TXN_TYPE":  "TC",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556517
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "240B233260990001",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "963",
        "DRCR_IND":  "D",
        "TRN_DESC":  "TRASLADO FONDOS SC",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  500000,
        "EXTERNAL_REF_NO":  "0991137034880050",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556425
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "240B233260990002",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "963",
        "DRCR_IND":  "D",
        "TRN_DESC":  "TRASLADO FONDOS SC",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  231,
        "EXTERNAL_REF_NO":  "0991144201273927",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556433
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278B2332609900DW",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "963",
        "DRCR_IND":  "D",
        "TRN_DESC":  "TRASLADO FONDOS SC",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  116116,
        "EXTERNAL_REF_NO":  "0991151528996116",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551515
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278B2332609900DX",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "963",
        "DRCR_IND":  "D",
        "TRN_DESC":  "TRASLADO FONDOS SC",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  118118,
        "EXTERNAL_REF_NO":  "0991154320209682",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551537
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278B233260990001",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "963",
        "DRCR_IND":  "D",
        "TRN_DESC":  "TRASLADO FONDOS SC",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  301,
        "EXTERNAL_REF_NO":  "0991145098686662",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551455
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "278B2332609900DW",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "486",
        "DRCR_IND":  "C",
        "TRN_DESC":  "TRASLADO DE FONDOS SC",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  116116,
        "EXTERNAL_REF_NO":  "0991151528996116",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551516
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "278B2332609900DX",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "486",
        "DRCR_IND":  "C",
        "TRN_DESC":  "TRASLADO DE FONDOS SC",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  118118,
        "EXTERNAL_REF_NO":  "0991154320209682",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551538
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "278B233260990001",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "486",
        "DRCR_IND":  "C",
        "TRN_DESC":  "TRASLADO DE FONDOS SC",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  301,
        "EXTERNAL_REF_NO":  "0991145098686662",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551456
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "240B233260990001",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "486",
        "DRCR_IND":  "C",
        "TRN_DESC":  "TRASLADO DE FONDOS SC",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  500000,
        "EXTERNAL_REF_NO":  "0991137034880050",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556426
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "240B233260990002",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "486",
        "DRCR_IND":  "C",
        "TRN_DESC":  "TRASLADO DE FONDOS SC",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  231,
        "EXTERNAL_REF_NO":  "0991144201273927",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556434
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "240B233260990001",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "A01",
        "DRCR_IND":  "D",
        "TRN_DESC":  "GMF",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  2000,
        "EXTERNAL_REF_NO":  "0991137034880050",
        "MODULE":  "RT",
        "TXN_TYPE":  "TM",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556429
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "240B233260990002",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "A01",
        "DRCR_IND":  "D",
        "TRN_DESC":  "GMF",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  0.92,
        "EXTERNAL_REF_NO":  "0991144201273927",
        "MODULE":  "RT",
        "TXN_TYPE":  "TM",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556437
    },
    {
        "AC_NO":  278822598,
        "TRN_REF_NO":  "278B233260990001",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "A01",
        "DRCR_IND":  "D",
        "TRN_DESC":  "GMF",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  1.2,
        "EXTERNAL_REF_NO":  "0991145098686662",
        "MODULE":  "RT",
        "TXN_TYPE":  "TM",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551459
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "278A0612609900DW",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "863",
        "DRCR_IND":  "C",
        "TRN_DESC":  "TRANSFERENCIA CR OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  111111,
        "EXTERNAL_REF_NO":  "0991148133693168",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551480
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "278A0612609900DX",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "863",
        "DRCR_IND":  "C",
        "TRN_DESC":  "TRANSFERENCIA CR OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  112112,
        "EXTERNAL_REF_NO":  "0991148509528098",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551492
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "278A0612609900DY",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "863",
        "DRCR_IND":  "C",
        "TRN_DESC":  "TRANSFERENCIA CR OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  119119,
        "EXTERNAL_REF_NO":  "0991155098158948",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551542
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "278A061260990001",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "863",
        "DRCR_IND":  "C",
        "TRN_DESC":  "TRANSFERENCIA CR OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  110001,
        "EXTERNAL_REF_NO":  "0991147311045561",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556454
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "278A061260990002",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "863",
        "DRCR_IND":  "C",
        "TRN_DESC":  "TRANSFERENCIA CR OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  113113,
        "EXTERNAL_REF_NO":  "0991149292408029",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556468
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "278A061260990003",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "863",
        "DRCR_IND":  "C",
        "TRN_DESC":  "TRANSFERENCIA CR OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  116116,
        "EXTERNAL_REF_NO":  "0991152360538751",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556492
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "278A061260990004",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "863",
        "DRCR_IND":  "C",
        "TRN_DESC":  "TRANSFERENCIA CR OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  117117,
        "EXTERNAL_REF_NO":  "0991153511212474",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556510
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "240A0612609900RR",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "863",
        "DRCR_IND":  "C",
        "TRN_DESC":  "TRANSFERENCIA CR OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  115115,
        "EXTERNAL_REF_NO":  "0991151039486392",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551504
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "240A061260990001",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "863",
        "DRCR_IND":  "C",
        "TRN_DESC":  "TRANSFERENCIA CR OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  100000,
        "EXTERNAL_REF_NO":  "0991146018845290",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551468
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "240A0612609900DW",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "863",
        "DRCR_IND":  "C",
        "TRN_DESC":  "TRANSFERENCIA CR OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  102301,
        "EXTERNAL_REF_NO":  "0991146470113142",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556442
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "240A0612609900DX",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "863",
        "DRCR_IND":  "C",
        "TRN_DESC":  "TRANSFERENCIA CR OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  114114,
        "EXTERNAL_REF_NO":  "0991150250478024",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556480
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "240A0612609900RR",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "862",
        "DRCR_IND":  "D",
        "TRN_DESC":  "TRANSFERENCIA DB OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  115115,
        "EXTERNAL_REF_NO":  "0991151039486392",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551503
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "240A061260990001",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "862",
        "DRCR_IND":  "D",
        "TRN_DESC":  "TRANSFERENCIA DB OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  100000,
        "EXTERNAL_REF_NO":  "0991146018845290",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551467
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "240A0612609900DW",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "862",
        "DRCR_IND":  "D",
        "TRN_DESC":  "TRANSFERENCIA DB OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  102301,
        "EXTERNAL_REF_NO":  "0991146470113142",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556441
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "240A0612609900DX",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "862",
        "DRCR_IND":  "D",
        "TRN_DESC":  "TRANSFERENCIA DB OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  114114,
        "EXTERNAL_REF_NO":  "0991150250478024",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556479
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A0612609900DW",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "862",
        "DRCR_IND":  "D",
        "TRN_DESC":  "TRANSFERENCIA DB OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  111111,
        "EXTERNAL_REF_NO":  "0991148133693168",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551479
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A0612609900DX",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "862",
        "DRCR_IND":  "D",
        "TRN_DESC":  "TRANSFERENCIA DB OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  112112,
        "EXTERNAL_REF_NO":  "0991148509528098",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551491
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A0612609900DY",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "862",
        "DRCR_IND":  "D",
        "TRN_DESC":  "TRANSFERENCIA DB OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  119119,
        "EXTERNAL_REF_NO":  "0991155098158948",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551541
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A061260990001",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "862",
        "DRCR_IND":  "D",
        "TRN_DESC":  "TRANSFERENCIA DB OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  110001,
        "EXTERNAL_REF_NO":  "0991147311045561",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556453
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A061260990002",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "862",
        "DRCR_IND":  "D",
        "TRN_DESC":  "TRANSFERENCIA DB OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  113113,
        "EXTERNAL_REF_NO":  "0991149292408029",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556467
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A061260990003",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "862",
        "DRCR_IND":  "D",
        "TRN_DESC":  "TRANSFERENCIA DB OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  116116,
        "EXTERNAL_REF_NO":  "0991152360538751",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556491
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A061260990004",
        "MEDIO_PAGO":  null,
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "862",
        "DRCR_IND":  "D",
        "TRN_DESC":  "TRANSFERENCIA DB OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  117117,
        "EXTERNAL_REF_NO":  "0991153511212474",
        "MODULE":  "RT",
        "TXN_TYPE":  "MT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556509
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "240A061260990001",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "818",
        "DRCR_IND":  "D",
        "TRN_DESC":  "COMISION TRANSF OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  35000,
        "EXTERNAL_REF_NO":  "0991146018845290",
        "MODULE":  "RT",
        "TXN_TYPE":  "CT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551474
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "240A0612609900RR",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "818",
        "DRCR_IND":  "D",
        "TRN_DESC":  "COMISION TRANSF OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  35000,
        "EXTERNAL_REF_NO":  "0991151039486392",
        "MODULE":  "RT",
        "TXN_TYPE":  "CT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551510
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "240A0612609900DW",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "818",
        "DRCR_IND":  "D",
        "TRN_DESC":  "COMISION TRANSF OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  35000,
        "EXTERNAL_REF_NO":  "0991146470113142",
        "MODULE":  "RT",
        "TXN_TYPE":  "CT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556448
    },
    {
        "AC_NO":  "240806828",
        "TRN_REF_NO":  "240A0612609900DX",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "818",
        "DRCR_IND":  "D",
        "TRN_DESC":  "COMISION TRANSF OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  35000,
        "EXTERNAL_REF_NO":  "0991150250478024",
        "MODULE":  "RT",
        "TXN_TYPE":  "CT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "0806828",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556486
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A0612609900DW",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "818",
        "DRCR_IND":  "D",
        "TRN_DESC":  "COMISION TRANSF OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  35000,
        "EXTERNAL_REF_NO":  "0991148133693168",
        "MODULE":  "RT",
        "TXN_TYPE":  "CT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551486
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A0612609900DX",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "818",
        "DRCR_IND":  "D",
        "TRN_DESC":  "COMISION TRANSF OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  35000,
        "EXTERNAL_REF_NO":  "0991148509528098",
        "MODULE":  "RT",
        "TXN_TYPE":  "CT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551498
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A0612609900DY",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "818",
        "DRCR_IND":  "D",
        "TRN_DESC":  "COMISION TRANSF OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  35000,
        "EXTERNAL_REF_NO":  "0991155098158948",
        "MODULE":  "RT",
        "TXN_TYPE":  "CT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633551548
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A061260990001",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "818",
        "DRCR_IND":  "D",
        "TRN_DESC":  "COMISION TRANSF OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  35000,
        "EXTERNAL_REF_NO":  "0991147311045561",
        "MODULE":  "RT",
        "TXN_TYPE":  "CT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556460
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A061260990002",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "818",
        "DRCR_IND":  "D",
        "TRN_DESC":  "COMISION TRANSF OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  35000,
        "EXTERNAL_REF_NO":  "0991149292408029",
        "MODULE":  "RT",
        "TXN_TYPE":  "CT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556474
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A061260990003",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "818",
        "DRCR_IND":  "D",
        "TRN_DESC":  "COMISION TRANSF OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  35000,
        "EXTERNAL_REF_NO":  "0991152360538751",
        "MODULE":  "RT",
        "TXN_TYPE":  "CT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556498
    },
    {
        "AC_NO":  "278822598",
        "TRN_REF_NO":  "278A061260990004",
        "MEDIO_PAGO":  "ACC",
        "EVENT":  "INIT",
        "TRN_DT":  46121,
        "VALUE_DT":  46121,
        "TRN_CODE":  "818",
        "DRCR_IND":  "D",
        "TRN_DESC":  "COMISION TRANSF OFICINA",
        "ID_BAN_NO_AVL":  null,
        "LLAVE_DEST":  null,
        "NOM_DES_NO_AVL":  null,
        "NOM_ORI_NO_AVL":  null,
        "ID_BAN_REP":  null,
        "INSTRUMENT_CODE":  null,
        "LCY_AMOUNT":  35000,
        "EXTERNAL_REF_NO":  "0991153511212474",
        "MODULE":  "RT",
        "TXN_TYPE":  "CT",
        "REFERENCIA1":  null,
        "REFERENCIA2":  null,
        "BRANCH":  "8822598",
        "IDENTIFICACION":  "0",
        "FACTURA":  "0",
        "INFO_LIBRE":  "0",
        "AC_ENTRY_SR_NO":  8633556516
    }
];

window.datosBancarios2 = datosBancarios2;

